# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'nl'
    mailer_default_from_email: "%env(MAILER_DEFAULT_FROM_EMAIL)%"
    mailer_default_from_name: "%env(MAILER_DEFAULT_FROM_NAME)%"
    zoho_crm_client_id: "%env(ZOHO_CRM_CLIENT_ID)%"
    zoho_crm_client_secret: "%env(ZOHO_CRM_CLIENT_SECRET)%"
    zoho_crm_redirect_uri: "%env(ZOHO_CRM_REDIRECT_URL)%"
    zoho_crm_currentUserEmail: "%env(ZOHO_CRM_CURRENT_USER_EMAIL)%" # @TODO should be from logged in user
    zoho_crm_log_path: "%kernel.project_dir%%env(ZOHO_CRM_LOG_PATH)%"
    zoho_crm_api_base_url: "%env(ZOHO_CRM_API_BASE_URL)%"
    zoho_crm_accounts_url: "%env(ZOHO_CRM_ACCOUNTS_URL)%"
    zoho_crm_grantToken: "%env(ZOHO_CRM_GRANT_TOKEN)%"
    zoho_crm_refreshToken: 'xx'
    zoho_books_organization_id: "%env(ZOHO_BOOKS_ORGANIZATION_ID)%"
    zoho.books.api.base_url: 'https://books.zoho.eu/api/v3/'
    zoho.crm.api.base_url: ''

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
                 $zohoCrmApiService: '@zoho.crm.api.service'
                 $zohoBooksApiService: '@zoho.books.api.service'
                 
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Doctrine\HashPasswordListener:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    App\Service\MailerService:
        arguments:
            - "@mailer"
            - "@twig"
            - "%env(MAILER_DEFAULT_FROM_EMAIL)%"
            - "%env(MAILER_DEFAULT_FROM_NAME)%"
            
    # makes classes in src/DataFixtures available to be used as services
    # and have a tag that allows actions to type-hint services
    App\DataFixtures\:
        resource: '../src/DataFixtures'
        tags: ['doctrine.fixture.orm']

    App\Service\Zoho\ContactsWebservice:
         arguments:
            - '%zoho_crm_client_id%'
            - '%zoho_crm_client_secret%'
            - '%zoho_crm_redirect_uri%'
            - '%zoho_crm_currentUserEmail%'
            - '%zoho_crm_log_path%'
            - '%zoho_crm_api_base_url%'
            - '%zoho_crm_accounts_url%'
            - '%zoho_crm_grantToken%'
            - '%zoho_crm_refreshToken%'

    App\Service\Zoho\BooksWebservice:
         arguments:
            - '%zoho_crm_client_id%'
            - '%zoho_crm_client_secret%'
            - '%zoho_crm_redirect_uri%'
            - '%zoho_crm_currentUserEmail%'
            - '%zoho_crm_log_path%'
            - '%zoho_crm_api_base_url%'
            - '%zoho_crm_accounts_url%'
            - '%zoho_crm_grantToken%'
            - '%zoho_crm_refreshToken%'
            
    App\Service\Zoho\ZohoAccessTokenService:
         arguments:
            - '%zoho_crm_client_id%'
            - '%zoho_crm_client_secret%'
            - '%zoho_crm_redirect_uri%'
            - '%zoho_crm_currentUserEmail%'
            - '%zoho_crm_log_path%'
            - '%zoho_crm_api_base_url%'
            - '%zoho_crm_accounts_url%'
            - '%zoho_crm_grantToken%'
            - '%zoho_crm_refreshToken%'
            
    zoho.books.api.service:
        class: App\Service\Zoho\ZohoApiService
        arguments:
            - '%zoho.books.api.base_url%'
            
    zoho.crm.api.service:
        class: App\Service\Zoho\ZohoApiService
        arguments:
            - '%zoho.crm.api.base_url%'